# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(max_length=18)),
                ('host_name', models.CharField(max_length=14)),
                ('loopback', models.CharField(max_length=15)),
                ('mac_address', models.CharField(max_length=17)),
                ('active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'tbl_router',
            },
        ),
    ]
